version: "3"

services:
  go:
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile
    container_name: docker_template_go
    environment:
      - TZ=Japan
    networks:
      - docker_template_network
    ports:
      - "80:8000"
    tty: true
    volumes:
      - ./app:/go/src/app
    working_dir: /go/src/app

networks:
  docker_template_network:
    external: true
